#!/bin/bash

set -e

BW=${BW:-100}
DURATION=${DURATION:-60}
CONGESTION=${CONGESTION:-prague}

# Create network namespaces
ip netns add ns1
ip netns add ns2

# Create veth pair
ip link add veth1 type veth peer name veth2

# Move interfaces to namespaces
ip link set veth1 netns ns1
ip link set veth2 netns ns2

# Configure IP addresses
ip netns exec ns1 ip addr add 10.0.0.1/24 dev veth1
ip netns exec ns2 ip addr add 10.0.0.2/24 dev veth2

# Bring up interfaces
ip netns exec ns1 ip link set veth1 up
ip netns exec ns2 ip link set veth2 up

# Disable offloading
ip netns exec ns1 ethtool -K veth1 tso off gso off gro off lro off
ip netns exec ns2 ethtool -K veth2 tso off gso off gro off lro off

# Set up HTB with DualPI2 on ns1
ip netns exec ns1 tc qdisc add dev veth1 root handle 1: htb default 10
ip netns exec ns1 tc class add dev veth1 parent 1: classid 1:10 htb rate "${BW}mbit" ceil "${BW}mbit" burst 1
ip netns exec ns1 tc qdisc add dev veth1 parent 1:10 handle 20: dualpi2

# Start iperf3 server in ns2
ip netns exec ns2 sysctl -qw net.ipv4.tcp_ecn=3
ip netns exec ns2 iperf3 --server --daemon

sleep 1

# Run iperf3 client in ns1
ip netns exec ns1 sysctl -qw net.ipv4.tcp_ecn=3
ip netns exec ns1 iperf3 --client 10.0.0.2 --time "$DURATION" --congestion "$CONGESTION" --json \
 | jq '[ .intervals[] | .streams[0] | { "time": .start, "cwnd": .snd_cwnd, "goodput": .bits_per_second, "rtt": .rtt } ]' \
 > "/vagrant/cwnd-${CONGESTION}.json"

# Print queues
ip netns exec ns1 tc -j -s qdisc show dev veth1 | jq '.[] | select(.handle == "20:")' \
 > "/vagrant/queue-${CONGESTION}.json"

# Cleanup
ip netns del ns1
ip netns del ns2
